language: scala
scala: 2.12.6
jdk: openjdk8

stages:
- name: test
- name: publish
  if: NOT type = pull_request

services:
  - docker

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
    - "$HOME/.coursier/cache"
    - ".hoarder-cache"

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "VtQ/Kkr9Cr63Sj8+mDVht5FPomgRVitlPS7vpQ9fdFk4yGF6QMhLlpx9BkWTm4PhYY42Tgpfqeu35rxeqWiMMXT3fd8M+BVFkGXvvxdNFwBMnBEjgIUa8eOmHxSxqQ7axKc3idOTbLn0lgJrA0M0xJJbwIMbfMM+j7vyuN6NBF0dY7Teak2xy73I3sNO/4VPAR076pvHMK+MD8+Wcc4DE6bDGyVj4umWkOb1+pB4Jl4gwtCXgBBsslkpfN20E/v+TAkXgabb/NBWvyUGQp9T+EmhZNVzTi73RwnNRa0aDp/2RL6oUFTGf4Er8T06v4oLqj1/z7V8j3X8gwkyB7TUcTk4ge8wPEkhWenPRRmOf8fUOUWsRqcxMzYiEmq7hYslVRrGur53SjWHooTxP2lEoNUegKt8K1KH5L6L2YsIL7tP9P+V+/60jA86sm7W6Ub2kHE0Fx6CSXsynu89192yyyxCTFMLmcr3ubp2H+gID/kLlwyPrbJHa3qJjKF1VRjJNuSaFo4lStcZe31zAJABZ+Gp09VdZGzDzpjF0LLtUsyyYowoEVB/Vu+QTVA+RgzIzuhdv2C31g/DPHjv6ML843OtC9CDlqYImTwWsgch6oTbD303MzaGpOO3M20RuK+XgUhbPDbYphgZ/H2Jgs3w0m5EX5fJWS+YOF6fqfncDbs="
    # GITHUB_TOKEN
    - secure: "TpDM12oFBfdGQ6kqSan4L3KcUuva48C3FMD8HupWS+jeI19xGPm32aybmNn7HqBSx/Hmb+MlRNmlw06DaRHtKz4braTLQyNnj37HObwNBaE8ofhT7fI5Y+J54higUbFBvqUUCwGH/3M7c3jTXkfnP46yAftgzHc0FE0CZfjZ0XZ5+rN15iwZlNypb2K1zi5mQj+OER9kOeeR/zQ3aY7bgj9yffZddT5mVJVpYCM9g/rzaTypwmb85/BgAE4/EhDscg2H/evL4j3mvztSh2zJRPP1m07Swm/4eEn3TDrX7F20zDI90tjeDHRoBmPdJyb47k1MUOi2921HbAdC/JQNcOwfJP5UxZpyGxVX8v2euYOn4w6O5tP1zJNNg7ATgwjr+nAGcMSNmJnemRzDVc5p0crnUmXfm5WRhPp46H4TpIXcmpDc+9pnY6bVKN5pMrH/ThOFsJcHJGjWmPOehgtAFlVcDoUbNRSuF7+H9j5jTUJyzp/p0+bSGlRZMgpRvZWKCwEf8Ac5j4W59AJWbsMi5FpG0FRDDZWdetExL8iPkABN5m8C488+76juAatVXUZxClvJVeLdWADPVpNuYcScOyohNk9We2MtcQY6eemZFptVBIbQ9+xG+72cZQboUmFDOQWYnpFg0WvoF7vRg6rV906BSq8lAoMklqfjpVC2TCk="
    # GITHUB_ACCESS_TOKEN
    - secure: "fteOjuFGQHAror+my4DSBYyeCV4iQVtqosFrOaGi0ceq0wVQGCSBKau4Y8PgK1/HjVWMr5tzmQG+a+JjhCn12q/CX0PagYvIGL+0FRxaMhJA0kRQTEQVxndP3ATwINRkz2fbGHOv2j6gkU1M37pLpbPbWoXHcc0SREwBQIs6mibCuWBM9hUYAUNNSHE2jJOolkAORtQ+aVz8M6/oZbjyybbijV0+z11vmeD+bSDdAx8pZAa0GV8sm7gerHIaIUAymy9GQdW3LWjsej55vMi21w4WSo+WZKwKThOUOA0p20O0W9yDZMrO+hU8HmXYAVhGOIgAr4dKMK8D4WsVcLRDV/tq0TE3HTAnUc7RYESlJZFEVHeUdK0jhr2XXpIhs/faGQuE9E4t4JnUUHibMr85JBSe2KZq21SHNLjjnh8jF6ncc3u7M3ZugdaRVnYFAdM/HDxDCwATlbNSNPHOntWQ/2n9FMU9AmE+7B2SPnIBJeq/8mF+B4ijdBJ+rba9rZDnIhbJQjd1pIJXOcmBJYhKXG2utLq8sJYpsGr1ZjCTSTLyynJ9UvfipzrEOfe5CSLI3UamNRrMM+Yg/7ekJIHaYBbHuetjZ4crMn1KV+cDsDlnRRkviktR8PU4TwOKQtyhgsUNTJqkQp9Kn2Tkw2vmf6LoMDEj/9LFwgHuJYmoFdQ="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "Tdo5hv1fq4SCg4/HSoGjdLAEY4fZQgQkD9S9pqpPUtrTInzgzO8lm+YYO+DwmjWHfSGz+Orr2fdrciYjymPWobKMAY3PGJHfKF7HGu+dXZAkYN1xOEBmfiXYkK4muy/pmknDu3j//8MMRmHQBvhgu55qinV/IO5LBNgIvq1RHm6veUa8pB8i5NRIy7Rg076cBFzeUM/LAVv5zvZqdYvIeXYtvJ+gNctr+PW+7n5grJF1kNRdB35zUJ7c4/UG1hWuyx+Aih26OARd8UG/EYXTbAjeFa+Ylor10mXAIMpa4/i5yYSMlxndLrox18aO+zY5Gxwz+grxUVBfyy1+j/XeYh+lluyNe6n7HWmjQ+2rxUKZ1AIfhMIYEj3q5rDCp/ievVBQtCCUyOslG3cNhptHWpErAkLu5kNf55cgqBqp1jEJoYsYqR81c3LNtCgLiR8Sn+wGByEcXdHJH+0hvZJtqPwLk4EXHsBwE4Ot7T5XYvZ9ChI8DqPksX7+95fYis4NRYWYoRuEBCwoHAn4Xdjk5p/VgzVAh/Bk897C9f3XlUoC481ww4X/N4RLVoyXYsoohHvqE/hrJzxv+rsjp8Jcvbfs4TCm5KBhw6mDnfb+r6sRIGtwDxELiB7wLFiwUImqMDAc7DWdO8gtkuwX687xsWPt1IbKbGbS6OvYVLWm+x4="

install:
  - mkdir scripts
  - $SBT transferCommonResources
  - scripts/commonSetup

jobs:
  include:
  - stage: test
    sudo: required
    script:
      # plain machine with mongodb on 27018 port
      - docker run -d -p 127.0.0.1:27018:27017 --name mongodb -e MONGODB_ROOT_PASSWORD=secret bitnami/mongodb:4.1.4
      # sshd can look at 27017 using `mng` host name, used to create tunnel like
      # ssh -f -N -L 33333:mng:27017 root@localhost -p 22222
      - docker-compose up -d
      - sudo apt-get update
      - sudo apt-get install sshpass
      - ssh-keygen -t rsa -N "passphrase" -f key_for_docker
      - sshpass -p root ssh-copy-id -i key_for_docker -o StrictHostKeyChecking=no root@localhost -p 22222
      - set -e
      - "$SBT ++$TRAVIS_SCALA_VERSION test"
  - stage: publish
    script:
      - set -e
      - "$SBT transferPublishAndTagResources"
      - TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar-datasource-mongo'
      - bumpInDownstream() { echo $1 > slamdata-mongo-version; }
      - bumpInDownstreamBench() { echo $1 > mongo-datasource-version; }
      - export -f bumpInDownstream
      - export -f bumpInDownstreamBench
      - scripts/bumpDependentProject slamdata slamx bumpInDownstream
      - scripts/bumpDependentProject slamdata benchmarks bumpInDownstreamBench
    git:
      depth: false

after_success:
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
  - master
  - "/^backport.*$/"

before_cache:
- find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
- find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
